import { type Locale, locales } from './paraglide/runtime';

export const UDMFlags = new Map<Locale, string>([
  ['af', 'circle-flags:lang-af'],
  ['am', 'circle-flags:lang-am'],
  ['ar', 'circle-flags:lang-ar'],
  ['hy-AM', 'circle-flags:lang-hy'],
  ['az-AZ', 'circle-flags:lang-az'],
  ['eu-ES', 'circle-flags:lang-eu'],
  ['be', 'circle-flags:lang-be'],
  ['bn-BD', 'circle-flags:lang-bn'],
  ['bg', 'circle-flags:lang-bg'],
  ['my-MM', 'circle-flags:lang-my'],
  ['ca', 'circle-flags:lang-ca'],
  ['zh-CN', 'circle-flags:lang-zh'],
  ['zh-TW', 'circle-flags:tw'],
  ['hr', 'circle-flags:lang-hr'],
  ['cs-CZ', 'circle-flags:lang-cs'],
  ['da-DK', 'circle-flags:lang-da'],
  ['nl-NL', 'circle-flags:lang-nl'],
  ['en-AU', 'circle-flags:au'],
  ['en-GB', 'circle-flags:en'],
  ['en-US', 'circle-flags:us'],
  ['et', 'circle-flags:lang-et'],
  ['fil', 'circle-flags:lang-fil'],
  ['fi-FI', 'circle-flags:lang-fi'],
  ['fr-FR', 'circle-flags:lang-fr'],
  ['fr-CA', 'circle-flags:ca-qc'],
  ['gl-ES', 'circle-flags:lang-gl'],
  ['ka-GE', 'circle-flags:lang-ka'],
  ['de-DE', 'circle-flags:lang-de'],
  ['el-GR', 'circle-flags:lang-el'],
  ['iw-IL', 'circle-flags:il'],
  ['hi-IN', 'circle-flags:lang-hi'],
  ['hu-HU', 'circle-flags:lang-hu'],
  ['is-IS', 'circle-flags:lang-is'],
  ['id', 'circle-flags:lang-id'],
  ['it-IT', 'circle-flags:lang-it'],
  ['ja-JP', 'circle-flags:lang-ja'],
  ['kn-IN', 'circle-flags:lang-kn'],
  ['km-KH', 'circle-flags:lang-km'],
  ['ko-KR', 'circle-flags:lang-ko'],
  ['ky-KG', 'circle-flags:lang-ky'],
  ['lo-LA', 'circle-flags:lang-lo'],
  ['lv', 'circle-flags:lang-lv'],
  ['lt', 'circle-flags:lang-lt'],
  ['mk-MK', 'circle-flags:lang-mk'],
  ['ms', 'circle-flags:lang-ms'],
  ['ml-IN', 'circle-flags:lang-ml'],
  ['mr-IN', 'circle-flags:lang-mr'],
  ['mn-MN', 'circle-flags:lang-mn'],
  ['ne-NP', 'circle-flags:lang-ne'],
  ['no-NO', 'circle-flags:lang-no'],
  ['fa', 'circle-flags:lang-fa'],
  ['pl-PL', 'circle-flags:lang-pl'],
  ['pt-BR', 'circle-flags:br'],
  ['pt-PT', 'circle-flags:lang-pt'],
  ['ro', 'circle-flags:lang-ro'],
  ['rm', 'circle-flags:lang-rm'],
  ['ru-RU', 'circle-flags:lang-ru'],
  ['sr', 'circle-flags:lang-sr'],
  ['si-LK', 'circle-flags:lang-si'],
  ['sk', 'circle-flags:lang-sk'],
  ['sl', 'circle-flags:lang-sl'],
  ['es-419', 'circle-flags:mx'],
  ['es-ES', 'circle-flags:lang-es'],
  ['es-US', 'circle-flags:lang-es'],
  ['sw', 'circle-flags:lang-sw'],
  ['sv-SE', 'circle-flags:lang-sv'],
  ['ta-IN', 'circle-flags:lang-ta'],
  ['te-IN', 'circle-flags:lang-te'],
  ['th', 'circle-flags:lang-th'],
  ['tr-TR', 'circle-flags:lang-tr'],
  ['uk', 'circle-flags:lang-uk'],
  ['vi', 'circle-flags:lang-vi'],
  ['sq', 'circle-flags:lang-sq'],
  ['zh-HK', 'circle-flags:hk'],
  ['en-CA', 'circle-flags:ca'],
  ['en-IN', 'circle-flags:lang-en-in'],
  ['en-SG', 'circle-flags:lang-en-sg'],
  ['en-ZA', 'circle-flags:lang-en-za'],
  ['gu', 'circle-flags:lang-gu'],
  ['kk', 'circle-flags:lang-kk'],
  ['ms-MY', 'circle-flags:lang-ms'],
  ['fa-AE', 'circle-flags:ae'],
  ['fa-AF', 'circle-flags:af'],
  ['fa-IR', 'circle-flags:ir'],
  ['pa', 'circle-flags:lang-pa'],
  ['ur', 'circle-flags:lang-ur'],
  ['zu', 'circle-flags:lang-zu']
]) as ReadonlyMap<Locale, string>;

export const AlternateCodes = new Map<Locale, Locale>([
  /* `iw-IL` is still used by GooglePlay, even though `he` is the most recent ISO 639 code */
  ['iw-IL', 'he' as Locale]
]) as ReadonlyMap<Locale, Locale>;

export function withAlternates() {
  return locales.concat(AlternateCodes.values().toArray());
}
