FROM otel/otel/opentelemetry-collector-contrib:0.131.1
COPY src/lib/otel/receivers_config.yaml /etc/otel/receivers_config.yaml
COPY src/lib/otel/production_config.yaml /etc/otel/production_config.yaml
CMD ["--config", "/etc/otel/production_config.yaml", "--config", "/etc/otel/receivers_config.yaml"]