receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:6317
      http:
        endpoint: 0.0.0.0:6318
exporters:
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug] # ISSUE: #1128 export to honeycomb in prod
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]